[tool.poetry]
name = "pharma_papers"
version = "0.1.0"
description = "A Python program to fetch research papers from PubMed based on user queries and identify authors with pharmaceutical affiliations."
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.1"
click = "^8.0.3"

[tool.poetry.scripts]
get-papers-list = "get-papers-list:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
